// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROGP2.Data;

#nullable disable

namespace PROGP2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018180327_AddStatusAndSeedData")]
    partial class AddStatusAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROGP2.Models.Claim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<byte[]>("RatePDF")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Hours = 8.5,
                            Rate = 150.0,
                            Status = "Pending",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Hours = 6.0,
                            Rate = 200.0,
                            Status = "Approved",
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            Hours = 10.0,
                            Rate = 175.0,
                            Status = "Declined",
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            Hours = 7.5,
                            Rate = 180.0,
                            Status = "Pending",
                            UserID = 3
                        },
                        new
                        {
                            ID = 5,
                            Hours = 9.0,
                            Rate = 160.0,
                            Status = "Approved",
                            UserID = 4
                        });
                });

            modelBuilder.Entity("PROGP2.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Name = "John Doe",
                            Password = "password123",
                            Role = "Employee",
                            UserName = "john.doe"
                        },
                        new
                        {
                            UserID = 2,
                            Name = "Jane Smith",
                            Password = "password123",
                            Role = "Employee",
                            UserName = "jane.smith"
                        },
                        new
                        {
                            UserID = 3,
                            Name = "Mike Johnson",
                            Password = "password123",
                            Role = "Manager",
                            UserName = "mike.johnson"
                        },
                        new
                        {
                            UserID = 4,
                            Name = "Sarah Wilson",
                            Password = "password123",
                            Role = "Employee",
                            UserName = "sarah.wilson"
                        },
                        new
                        {
                            UserID = 5,
                            Name = "System Administrator",
                            Password = "admin123",
                            Role = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("PROGP2.Models.Claim", b =>
                {
                    b.HasOne("PROGP2.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROGP2.Models.User", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
